/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import entity.Project;
import javax.swing.JOptionPane;
import model.ProjectBO;

/**
 *
 * @author Sun of Vn
 */
public class FrmModifyProject extends javax.swing.JFrame {
    private int add=0;
    private int edit=1;
    private int projectID=-1;
    FrmAdminForm parent;
    private int modifyMode;
    /**
     * Creates new form FrmModifyProject
     */
    public FrmModifyProject(int modifyMode,int projectID) {
        initComponents();
        this.setLocationRelativeTo( null );
        this.modifyMode=modifyMode;
        this.projectID=projectID;
        if(modifyMode==add){
        lbProjectID.setVisible(false);
        lbprojID.setVisible(false);
        btDelete.setVisible(false);
        }
        if(modifyMode==edit){
            btModify.setText("Edit");
            ProjectBO bo=new ProjectBO();
            Project prj=bo.getProject(projectID);
            lbProjectID.setText(prj.getProjectID()+"");
            txtDescription.setText(prj.getDescription());
            txtProjectName.setText(prj.getProjectName());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btModify = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtProjectName = new javax.swing.JTextField();
        txtDescription = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        lbprojID = new javax.swing.JLabel();
        lbProjectID = new javax.swing.JLabel();
        btDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Modify project page");

        btModify.setText("Add");
        btModify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btModifyActionPerformed(evt);
            }
        });

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("Name");

        jLabel2.setText("Description");

        lbprojID.setText("ProjectID");

        btDelete.setText("Delete");
        btDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(btModify)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btDelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(lbprojID))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtProjectName, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbProjectID))
                        .addGap(0, 9, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbprojID)
                    .addComponent(lbProjectID))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtProjectName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btModify)
                    .addComponent(jButton2)
                    .addComponent(btDelete))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btModifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btModifyActionPerformed
if(txtProjectName.getText().trim().length()>0){
            Project prj=new Project(projectID,txtProjectName.getText(),txtDescription.getText());
        ProjectBO bo=new ProjectBO();
        if(modifyMode==add)
         if(bo.insertProject(prj))
       {
           parent.refresh();
           JOptionPane.showMessageDialog(this,"Add project successful");
           this.dispose();
       }
        if(modifyMode==edit)
         if(bo.updateProject(prj))
       {
           parent.refresh();
           JOptionPane.showMessageDialog(this,"Edit project successful");
           this.dispose();
       }
}else JOptionPane.showMessageDialog(this,"Project name cant be empty");
    }//GEN-LAST:event_btModifyActionPerformed

    private void btDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeleteActionPerformed
                 int dialogButton = JOptionPane.YES_NO_OPTION;
       int dialogResult = JOptionPane.showConfirmDialog (null, "Would You Like to delete this project?","Warning",dialogButton);
        if(dialogResult == JOptionPane.YES_OPTION){
        ProjectBO bo=new ProjectBO();
            if(bo.deleteProject(new int[]{projectID}))
            {
            JOptionPane.showMessageDialog(rootPane, "Delete success!");
                parent.refresh();
                this.dispose();
            }else JOptionPane.showMessageDialog(rootPane, "Delete fail!");
        }
    }//GEN-LAST:event_btDeleteActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btDelete;
    private javax.swing.JButton btModify;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lbProjectID;
    private javax.swing.JLabel lbprojID;
    private javax.swing.JTextField txtDescription;
    private javax.swing.JTextField txtProjectName;
    // End of variables declaration//GEN-END:variables

    void setParent(FrmAdminForm aThis) {
        parent=aThis;
    }
}
